/* eslint-disable */
// This file is auto-generated by scripts/cache-blogs.ts
// Do not edit this file directly.

import type { Blog } from "@/schema/blog";

export const allBlogs: Blog[] = [
  {
    "metadata": {
      "title": "Häufige Fehler bei der Kinderernährung: Vom Säuglingsalter bis zur Adoleszenz",
      "description": "Vom Säuglingsalter bis zum Ende der Adoleszenz können Ernährungsfehler der Eltern sowohl zu Unterernährung als auch zu Übergewicht bei Kindern führen. Dieser Artikel beleuchtet mit einem wissenschaftlichen und narrativen Ansatz die wichtigsten gängigen Fehler von Eltern bei der Ernährung von Kindern und Jugendlichen sowie einfache und praktische Strategien zu deren Korrektur.",
      "keywords": [
        "Kinderernährung",
        "Säuglingsernährung",
        "Ernährung von Jugendlichen",
        "Ernährungsfehler",
        "Esserziehung",
        "Gesunde Ernährung"
      ],
      "locale": "de",
      "sharedSlug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "id": 1,
      "slug": "häufige-fehler-bei-der-kinderernaehrung-vom-saeuglingsalter-bis-zur-adoleszenz",
      "image": "/blogs/common-child-nutrition-mistakes-from-infancy-to-adolescence/11.jpeg",
      "author": "Houman Khoshbin",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "Kinderheilkunde",
        "Kinderernährung",
        "Ernährung_Jugendlicher",
        "Kinderwachstum",
        "Gesunde_Ernährung"
      ],
      "resources": [
        {
          "label": "WHO - Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO - Obesity and overweight",
          "url": "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"
        },
        {
          "label": "WHO - Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "AAP / HealthyChildren - Fruit juice in infants, children, and adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Fruit-Juice-and-Your-Childs-Diet.aspx"
        },
        {
          "label": "CDC - Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "CDC - Youth Risk Behavior Survey",
          "url": "https://www.cdc.gov/healthyyouth/data/yrbs/"
        },
        {
          "label": "WHO - Oral health",
          "url": "https://www.who.int/news-room/fact-sheets/detail/oral-health"
        },
        {
          "label": "Michigan Medicine - Picky eating in toddlers",
          "url": "https://www.michiganmedicine.org/health-lab/picky-eaters"
        },
        {
          "label": "EurekAlert - American toddlers and added sugar",
          "url": "https://www.eurekalert.org/news-releases/821843"
        },
        {
          "label": "JAMA Pediatrics - Eating family meals together at home",
          "url": "https://jamanetwork.com/journals/jamapediatrics"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 4843,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Ernährung von Säuglingen (0 bis 12 Monate): Die Grundlagen gesunder Gewohnheiten von den ersten Bissen an",
        "id": "ernährung-von-säuglingen-0-bis-12-monate-die-grundlagen-gesunder-gewohnheiten-von-den-ersten-bissen-an"
      },
      {
        "depth": 2,
        "value": "Ernährung von Kleinkindern (1 bis 3 Jahre): Umgang mit wählerischem Essverhalten und Unabhängigkeitsdrang",
        "id": "ernährung-von-kleinkindern-1-bis-3-jahre-umgang-mit-wählerischem-essverhalten-und-unabhängigkeitsdrang"
      },
      {
        "depth": 2,
        "value": "Ernährung von Vorschulkindern (3 bis 5 Jahre): Die Gestaltung von Essgewohnheiten",
        "id": "ernährung-von-vorschulkindern-3-bis-5-jahre-die-gestaltung-von-essgewohnheiten"
      },
      {
        "depth": 2,
        "value": "Ernährung von Schulkindern (6 bis 12 Jahre): Entwicklung von Unabhängigkeit bei der Auswahl",
        "id": "ernährung-von-schulkindern-6-bis-12-jahre-entwicklung-von-unabhängigkeit-bei-der-auswahl"
      },
      {
        "depth": 2,
        "value": "Ernährung von Jugendlichen (13 bis 18 Jahre): Balance zwischen Unabhängigkeit und Aufsicht",
        "id": "ernährung-von-jugendlichen-13-bis-18-jahre-balance-zwischen-unabhängigkeit-und-aufsicht"
      },
      {
        "depth": 2,
        "value": "Abschließende Bemerkung",
        "id": "abschließende-bemerkung"
      }
    ]
  },
  {
    "metadata": {
      "title": "Common Child Nutrition Mistakes: From Infancy to Adolescence",
      "description": "From infancy to the end of adolescence, parental nutritional mistakes can lead to both malnutrition and overweight in children. In this article, with a scientific and narrative perspective, the most important common mistakes parents make in the nutrition of children and adolescents, along with simple and practical solutions for their correction, are examined.",
      "keywords": [
        "child nutrition",
        "infant nutrition",
        "adolescent nutrition",
        "nutritional mistakes",
        "food education",
        "healthy eating"
      ],
      "locale": "en",
      "sharedSlug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "id": 2,
      "slug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "image": "/blogs/common-child-nutrition-mistakes-from-infancy-to-adolescence/11.jpeg",
      "author": "Houman Khoshbin",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "pediatrics",
        "child_nutrition",
        "adolescent_nutrition",
        "child_growth",
        "healthy_eating"
      ],
      "resources": [
        {
          "label": "WHO - Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO - Obesity and overweight",
          "url": "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"
        },
        {
          "label": "WHO - Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "AAP / HealthyChildren - Fruit juice in infants, children, and adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Fruit-Juice-and-Your-Childs-Diet.aspx"
        },
        {
          "label": "CDC - Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "CDC - Youth Risk Behavior Survey",
          "url": "https://www.cdc.gov/healthyyouth/data/yrbs/"
        },
        {
          "label": "WHO - Oral health",
          "url": "https://www.who.int/news-room/fact-sheets/detail/oral-health"
        },
        {
          "label": "Michigan Medicine - Picky eating in toddlers",
          "url": "https://www.michiganmedicine.org/health-lab/picky-eaters"
        },
        {
          "label": "EurekAlert - American toddlers and added sugar",
          "url": "https://www.eurekalert.org/news-releases/821843"
        },
        {
          "label": "JAMA Pediatrics - Eating family meals together at home",
          "url": "https://jamanetwork.com/journals/jamapediatrics"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 4912,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "Infant Nutrition (0 to 12 Months): The Foundations of Healthy Habits from the First Bites",
        "id": "infant-nutrition-0-to-12-months-the-foundations-of-healthy-habits-from-the-first-bites"
      },
      {
        "depth": 2,
        "value": "Toddler Nutrition (1 to 3 Years): Managing Picky Eating and Independence",
        "id": "toddler-nutrition-1-to-3-years-managing-picky-eating-and-independence"
      },
      {
        "depth": 2,
        "value": "Preschooler Nutrition (3 to 5 Years): Shaping Eating Habits",
        "id": "preschooler-nutrition-3-to-5-years-shaping-eating-habits"
      },
      {
        "depth": 2,
        "value": "Elementary Schooler Nutrition (6 to 12 Years): Developing Independence in Choice",
        "id": "elementary-schooler-nutrition-6-to-12-years-developing-independence-in-choice"
      },
      {
        "depth": 2,
        "value": "Adolescent Nutrition (13 to 18 Years): Balance Between Independence and Supervision",
        "id": "adolescent-nutrition-13-to-18-years-balance-between-independence-and-supervision"
      },
      {
        "depth": 2,
        "value": "Concluding Remarks",
        "id": "concluding-remarks"
      }
    ]
  },
  {
    "metadata": {
      "title": "اشتباهات رایج تغذیه کودک؛ از نوزادی تا نوجوانی",
      "description": "از نوزادی تا پایان نوجوانی، اشتباهات تغذیه‌ای والدین می‌تواند هم به سوءتغذیه و هم به اضافه‌وزن کودکان منجر شود. در این مقاله، با نگاهی علمی و روایت‌محور، مهم‌ترین خطاهای رایج والدین در تغذیهٔ کودکان و نوجوانان و راهکارهای ساده و عملی برای اصلاح آن‌ها بررسی می‌شود.",
      "keywords": [
        "تغذیه کودک",
        "تغذیه نوزاد",
        "تغذیه نوجوان",
        "اشتباهات تغذیه‌ای",
        "تربیت غذایی",
        "تغذیه سالم"
      ],
      "locale": "fa",
      "sharedSlug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "id": 3,
      "slug": "اشتباهات-رایج-تغذیه-کودک-از-نوزادی-تا-نوجوانی",
      "image": "/blogs/common-child-nutrition-mistakes-from-infancy-to-adolescence/11.jpeg",
      "author": "هومان خوش بین",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "پزشکی_کودکان",
        "تغذیه_کودک",
        "تغذیه_نوجوان",
        "رشد_کودک",
        "تغذیه_سالم"
      ],
      "resources": [
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO – Obesity and overweight",
          "url": "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "AAP / HealthyChildren – Fruit juice in infants, children, and adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Fruit-Juice-and-Your-Childs-Diet.aspx"
        },
        {
          "label": "CDC – Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "CDC – Youth Risk Behavior Survey",
          "url": "https://www.cdc.gov/healthyyouth/data/yrbs/"
        },
        {
          "label": "WHO – Oral health",
          "url": "https://www.who.int/news-room/fact-sheets/detail/oral-health"
        },
        {
          "label": "Michigan Medicine – Picky eating in toddlers",
          "url": "https://www.michiganmedicine.org/health-lab/picky-eaters"
        },
        {
          "label": "EurekAlert – American toddlers and added sugar",
          "url": "https://www.eurekalert.org/news-releases/821843"
        },
        {
          "label": "JAMA Pediatrics – Eating family meals together at home",
          "url": "https://jamanetwork.com/journals/jamapediatrics"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 5205,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "تغذیه نوزادان (۰ تا ۱۲ ماهگی): پایه‌های عادت‌های سالم از اولین لقمه‌ها",
        "id": "تغذیه-نوزادان-۰-تا-۱۲-ماهگی-پایههای-عادتهای-سالم-از-اولین-لقمهها"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان نوپا (۱ تا ۳ سال): مدیریت بدغذایی و استقلال‌طلبی",
        "id": "تغذیه-کودکان-نوپا-۱-تا-۳-سال-مدیریت-بدغذایی-و-استقلالطلبی"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان پیش‌دبستانی (۳ تا ۵ سال): شکل‌گیری عادت‌های غذا خوردن",
        "id": "تغذیه-کودکان-پیشدبستانی-۳-تا-۵-سال-شکلگیری-عادتهای-غذا-خوردن"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان دبستانی (۶ تا ۱۲ سال): شکل‌گیری استقلال در انتخاب",
        "id": "تغذیه-کودکان-دبستانی-۶-تا-۱۲-سال-شکلگیری-استقلال-در-انتخاب"
      },
      {
        "depth": 2,
        "value": "تغذیه نوجوانان (۱۳ تا ۱۸ سال): تعادل بین استقلال و نظارت",
        "id": "تغذیه-نوجوانان-۱۳-تا-۱۸-سال-تعادل-بین-استقلال-و-نظارت"
      },
      {
        "depth": 2,
        "value": "سخن پایانی",
        "id": "سخن-پایانی"
      }
    ]
  }
];
