/* eslint-disable */
// This file is auto-generated by scripts/cache-blogs.ts
// Do not edit this file directly.

import type { Blog } from "@/schema/blog";

export const allBlogs: Blog[] = [
  {
    "metadata": {
      "title": "Häufige Fehler bei der Kinderernährung: Vom Säuglingsalter bis zur Adoleszenz",
      "description": "Vom Säuglingsalter bis zum Ende der Adoleszenz können Ernährungsfehler der Eltern sowohl zu Unterernährung als auch zu Übergewicht bei Kindern führen. Dieser Artikel beleuchtet mit einem wissenschaftlichen und narrativen Ansatz die wichtigsten gängigen Fehler von Eltern bei der Ernährung von Kindern und Jugendlichen sowie einfache und praktische Strategien zu deren Korrektur.",
      "keywords": [
        "Kinderernährung",
        "Säuglingsernährung",
        "Ernährung von Jugendlichen",
        "Ernährungsfehler",
        "Esserziehung",
        "Gesunde Ernährung"
      ],
      "locale": "de",
      "sharedSlug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "id": 1,
      "slug": "häufige-fehler-bei-der-kinderernaehrung-vom-saeuglingsalter-bis-zur-adoleszenz",
      "image": "/blogs/common-child-nutrition-mistakes-from-infancy-to-adolescence/11.jpeg",
      "author": "Houman Khoshbin",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "Kinderheilkunde",
        "Kinderernährung",
        "Ernährung_Jugendlicher",
        "Kinderwachstum",
        "Gesunde_Ernährung"
      ],
      "resources": [
        {
          "label": "WHO - Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO - Obesity and overweight",
          "url": "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"
        },
        {
          "label": "WHO - Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "AAP / HealthyChildren - Fruit juice in infants, children, and adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Fruit-Juice-and-Your-Childs-Diet.aspx"
        },
        {
          "label": "CDC - Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "CDC - Youth Risk Behavior Survey",
          "url": "https://www.cdc.gov/healthyyouth/data/yrbs/"
        },
        {
          "label": "WHO - Oral health",
          "url": "https://www.who.int/news-room/fact-sheets/detail/oral-health"
        },
        {
          "label": "Michigan Medicine - Picky eating in toddlers",
          "url": "https://www.michiganmedicine.org/health-lab/picky-eaters"
        },
        {
          "label": "EurekAlert - American toddlers and added sugar",
          "url": "https://www.eurekalert.org/news-releases/821843"
        },
        {
          "label": "JAMA Pediatrics - Eating family meals together at home",
          "url": "https://jamanetwork.com/journals/jamapediatrics"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 4843,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Ernährung von Säuglingen (0 bis 12 Monate): Die Grundlagen gesunder Gewohnheiten von den ersten Bissen an",
        "id": "ernährung-von-säuglingen-0-bis-12-monate-die-grundlagen-gesunder-gewohnheiten-von-den-ersten-bissen-an"
      },
      {
        "depth": 2,
        "value": "Ernährung von Kleinkindern (1 bis 3 Jahre): Umgang mit wählerischem Essverhalten und Unabhängigkeitsdrang",
        "id": "ernährung-von-kleinkindern-1-bis-3-jahre-umgang-mit-wählerischem-essverhalten-und-unabhängigkeitsdrang"
      },
      {
        "depth": 2,
        "value": "Ernährung von Vorschulkindern (3 bis 5 Jahre): Die Gestaltung von Essgewohnheiten",
        "id": "ernährung-von-vorschulkindern-3-bis-5-jahre-die-gestaltung-von-essgewohnheiten"
      },
      {
        "depth": 2,
        "value": "Ernährung von Schulkindern (6 bis 12 Jahre): Entwicklung von Unabhängigkeit bei der Auswahl",
        "id": "ernährung-von-schulkindern-6-bis-12-jahre-entwicklung-von-unabhängigkeit-bei-der-auswahl"
      },
      {
        "depth": 2,
        "value": "Ernährung von Jugendlichen (13 bis 18 Jahre): Balance zwischen Unabhängigkeit und Aufsicht",
        "id": "ernährung-von-jugendlichen-13-bis-18-jahre-balance-zwischen-unabhängigkeit-und-aufsicht"
      },
      {
        "depth": 2,
        "value": "Abschließende Bemerkung",
        "id": "abschließende-bemerkung"
      }
    ]
  },
  {
    "metadata": {
      "title": "Common Child Nutrition Mistakes: From Infancy to Adolescence",
      "description": "From infancy to the end of adolescence, parental nutritional mistakes can lead to both malnutrition and overweight in children. In this article, with a scientific and narrative perspective, the most important common mistakes parents make in the nutrition of children and adolescents, along with simple and practical solutions for their correction, are examined.",
      "keywords": [
        "child nutrition",
        "infant nutrition",
        "adolescent nutrition",
        "nutritional mistakes",
        "food education",
        "healthy eating"
      ],
      "locale": "en",
      "sharedSlug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "id": 2,
      "slug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "image": "/blogs/common-child-nutrition-mistakes-from-infancy-to-adolescence/11.jpeg",
      "author": "Houman Khoshbin",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "pediatrics",
        "child_nutrition",
        "adolescent_nutrition",
        "child_growth",
        "healthy_eating"
      ],
      "resources": [
        {
          "label": "WHO - Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO - Obesity and overweight",
          "url": "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"
        },
        {
          "label": "WHO - Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "AAP / HealthyChildren - Fruit juice in infants, children, and adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Fruit-Juice-and-Your-Childs-Diet.aspx"
        },
        {
          "label": "CDC - Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "CDC - Youth Risk Behavior Survey",
          "url": "https://www.cdc.gov/healthyyouth/data/yrbs/"
        },
        {
          "label": "WHO - Oral health",
          "url": "https://www.who.int/news-room/fact-sheets/detail/oral-health"
        },
        {
          "label": "Michigan Medicine - Picky eating in toddlers",
          "url": "https://www.michiganmedicine.org/health-lab/picky-eaters"
        },
        {
          "label": "EurekAlert - American toddlers and added sugar",
          "url": "https://www.eurekalert.org/news-releases/821843"
        },
        {
          "label": "JAMA Pediatrics - Eating family meals together at home",
          "url": "https://jamanetwork.com/journals/jamapediatrics"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 4912,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "Infant Nutrition (0 to 12 Months): The Foundations of Healthy Habits from the First Bites",
        "id": "infant-nutrition-0-to-12-months-the-foundations-of-healthy-habits-from-the-first-bites"
      },
      {
        "depth": 2,
        "value": "Toddler Nutrition (1 to 3 Years): Managing Picky Eating and Independence",
        "id": "toddler-nutrition-1-to-3-years-managing-picky-eating-and-independence"
      },
      {
        "depth": 2,
        "value": "Preschooler Nutrition (3 to 5 Years): Shaping Eating Habits",
        "id": "preschooler-nutrition-3-to-5-years-shaping-eating-habits"
      },
      {
        "depth": 2,
        "value": "Elementary Schooler Nutrition (6 to 12 Years): Developing Independence in Choice",
        "id": "elementary-schooler-nutrition-6-to-12-years-developing-independence-in-choice"
      },
      {
        "depth": 2,
        "value": "Adolescent Nutrition (13 to 18 Years): Balance Between Independence and Supervision",
        "id": "adolescent-nutrition-13-to-18-years-balance-between-independence-and-supervision"
      },
      {
        "depth": 2,
        "value": "Concluding Remarks",
        "id": "concluding-remarks"
      }
    ]
  },
  {
    "metadata": {
      "title": "اشتباهات رایج تغذیه کودک؛ از نوزادی تا نوجوانی",
      "description": "از نوزادی تا پایان نوجوانی، اشتباهات تغذیه‌ای والدین می‌تواند هم به سوءتغذیه و هم به اضافه‌وزن کودکان منجر شود. در این مقاله، با نگاهی علمی و روایت‌محور، مهم‌ترین خطاهای رایج والدین در تغذیهٔ کودکان و نوجوانان و راهکارهای ساده و عملی برای اصلاح آن‌ها بررسی می‌شود.",
      "keywords": [
        "تغذیه کودک",
        "تغذیه نوزاد",
        "تغذیه نوجوان",
        "اشتباهات تغذیه‌ای",
        "تربیت غذایی",
        "تغذیه سالم"
      ],
      "locale": "fa",
      "sharedSlug": "common-child-nutrition-mistakes-from-infancy-to-adolescence",
      "id": 3,
      "slug": "اشتباهات-رایج-تغذیه-کودک-از-نوزادی-تا-نوجوانی",
      "image": "/blogs/common-child-nutrition-mistakes-from-infancy-to-adolescence/11.jpeg",
      "author": "هومان خوش بین",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "پزشکی_کودکان",
        "تغذیه_کودک",
        "تغذیه_نوجوان",
        "رشد_کودک",
        "تغذیه_سالم"
      ],
      "resources": [
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO – Obesity and overweight",
          "url": "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "AAP / HealthyChildren – Fruit juice in infants, children, and adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Fruit-Juice-and-Your-Childs-Diet.aspx"
        },
        {
          "label": "CDC – Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "CDC – Youth Risk Behavior Survey",
          "url": "https://www.cdc.gov/healthyyouth/data/yrbs/"
        },
        {
          "label": "WHO – Oral health",
          "url": "https://www.who.int/news-room/fact-sheets/detail/oral-health"
        },
        {
          "label": "Michigan Medicine – Picky eating in toddlers",
          "url": "https://www.michiganmedicine.org/health-lab/picky-eaters"
        },
        {
          "label": "EurekAlert – American toddlers and added sugar",
          "url": "https://www.eurekalert.org/news-releases/821843"
        },
        {
          "label": "JAMA Pediatrics – Eating family meals together at home",
          "url": "https://jamanetwork.com/journals/jamapediatrics"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 5205,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "تغذیه نوزادان (۰ تا ۱۲ ماهگی): پایه‌های عادت‌های سالم از اولین لقمه‌ها",
        "id": "تغذیه-نوزادان-۰-تا-۱۲-ماهگی-پایههای-عادتهای-سالم-از-اولین-لقمهها"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان نوپا (۱ تا ۳ سال): مدیریت بدغذایی و استقلال‌طلبی",
        "id": "تغذیه-کودکان-نوپا-۱-تا-۳-سال-مدیریت-بدغذایی-و-استقلالطلبی"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان پیش‌دبستانی (۳ تا ۵ سال): شکل‌گیری عادت‌های غذا خوردن",
        "id": "تغذیه-کودکان-پیشدبستانی-۳-تا-۵-سال-شکلگیری-عادتهای-غذا-خوردن"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان دبستانی (۶ تا ۱۲ سال): شکل‌گیری استقلال در انتخاب",
        "id": "تغذیه-کودکان-دبستانی-۶-تا-۱۲-سال-شکلگیری-استقلال-در-انتخاب"
      },
      {
        "depth": 2,
        "value": "تغذیه نوجوانان (۱۳ تا ۱۸ سال): تعادل بین استقلال و نظارت",
        "id": "تغذیه-نوجوانان-۱۳-تا-۱۸-سال-تعادل-بین-استقلال-و-نظارت"
      },
      {
        "depth": 2,
        "value": "سخن پایانی",
        "id": "سخن-پایانی"
      }
    ]
  },
  {
    "metadata": {
      "title": "Nahrungsergänzungsmittel für das Wachstum – ein umfassender Leitfaden für Familien",
      "description": "In diesem Artikel betrachten wir mit einem wissenschaftlichen, aber gut verständlichen Blick für Familien verschiedene Nahrungsergänzungsmittel, die das Wachstum von Kindern und Jugendlichen beeinflussen können (Vitamine, Mineralstoffe, Proteine, Omega-3 usw.), die wichtigsten Punkte beim Kauf und bei der Einnahme sowie Sicherheitswarnungen – mit der ständigen Betonung, dass jedes Präparat ausschließlich mit ärztlicher Verordnung und unter ärztlicher Aufsicht eingenommen werden sollte.",
      "keywords": [
        "kinderheilkunde",
        "kinderernaehrung",
        "wachstumspraeparat",
        "kindliches wachstum"
      ],
      "locale": "de",
      "sharedSlug": "growth-supplements-guide-for-families",
      "id": 21,
      "slug": "nahrungsergaenzungsmittel-fuer-das-wachstum-leitfaden-fuer-familien",
      "image": "/blogs/growth-supplements-guide-for-families/0.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-30T20:30:00.000Z",
      "category": "general-health",
      "tags": [
        "Kinderheilkunde",
        "Kinderernährung",
        "Wachstumspräparat",
        "Wachstum_Kind"
      ],
      "resources": [
        {
          "label": "HealthyChildren (AAP) – Vitamin supplements for children",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Where-We-Stand-Vitamins.aspx"
        },
        {
          "label": "HealthyChildren (AAP) – Vitamin D for babies, children & adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/vitamin-d-on-the-double.aspx"
        },
        {
          "label": "Mayo Clinic – Vitamin A: side effects & dosage",
          "url": "https://www.mayoclinic.org/drugs-supplements/vitamin-a-oral-route-intramuscular-route/description/drg-80000155"
        },
        {
          "label": "Mayo Clinic – Multivitamins: Do young children need them?",
          "url": "https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/expert-answers/multivitamins/faq-20058310"
        },
        {
          "label": "Healthline – How to increase height: Is it possible?",
          "url": "https://www.healthline.com/health/how-to-increase-height"
        },
        {
          "label": "Mayo Clinic – Iron deficiency in children: Prevention tips for parents",
          "url": "https://www.mayoclinic.org/healthy-lifestyle/childrens-health/in-depth/iron-deficiency/art-20045634"
        },
        {
          "label": "WHO – Zinc supplementation and growth in children",
          "url": "https://www.who.int/tools/elena/bbc/zinc-stunting"
        },
        {
          "label": "Mayo Clinic Health System – Can kids safely use supplements?",
          "url": "https://www.mayoclinichealthsystem.org/hometown-health/speaking-of-health/is-it-safe-for-my-kid-to-take-supplements"
        },
        {
          "label": "Mayo Clinic News Network – Omega-3 supplements for children",
          "url": "https://newsnetwork.mayoclinic.org/discussion/mayo-clinic-q-and-a-omega-3-supplements-for-children-what-does-the-research-show/"
        },
        {
          "label": "NCCIH – Dietary supplements for children and teens",
          "url": "https://www.nccih.nih.gov/health/tips/things-to-know-about-dietary-supplements-for-children-and-teens"
        }
      ],
      "related": [
        "vitamins-and-minerals-for-healthy-child-growth",
        "protein-key-to-child-growth"
      ],
      "suggested": [
        "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
        "healthy-teen-nutrition-a-comprehensive-guide-for-parents"
      ],
      "approvedBy": "Dr. Hossein Lavasanifar",
      "titleGradientIndices": [
        0,
        3,
        5
      ]
    },
    "wordCount": 5005,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Arten von Ergänzungsmitteln, die mit Wachstum zu tun haben",
        "id": "arten-von-ergänzungsmitteln-die-mit-wachstum-zu-tun-haben"
      },
      {
        "depth": 2,
        "value": "Hinweise zum Kauf und zur Einnahme von Ergänzungsmitteln",
        "id": "hinweise-zum-kauf-und-zur-einnahme-von-ergänzungsmitteln"
      },
      {
        "depth": 2,
        "value": "Warnhinweise und Vorsichtsmaßnahmen",
        "id": "warnhinweise-und-vorsichtsmaßnahmen"
      },
      {
        "depth": 2,
        "value": "Fazit",
        "id": "fazit"
      }
    ]
  },
  {
    "metadata": {
      "title": "Dietary Supplements for Growth: A Comprehensive Guide for Families",
      "description": "In this article, we take a scientific yet family-friendly look at dietary supplements that may affect the growth of children and teens (vitamins, minerals, proteins, omega-3, etc.), key points about buying and using them, and important safety warnings—with constant emphasis that every supplement must only be used with a doctor’s prescription and supervision.",
      "keywords": [
        "pediatrics",
        "child nutrition",
        "growth supplement",
        "child growth"
      ],
      "locale": "en",
      "sharedSlug": "growth-supplements-guide-for-families",
      "id": 20,
      "slug": "growth-supplements-guide-for-families",
      "image": "/blogs/growth-supplements-guide-for-families/0.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-30T20:30:00.000Z",
      "category": "general-health",
      "tags": [
        "pediatric_medicine",
        "child_nutrition",
        "growth_supplement",
        "child_growth"
      ],
      "resources": [
        {
          "label": "HealthyChildren (AAP) – Vitamin supplements for children",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Where-We-Stand-Vitamins.aspx"
        },
        {
          "label": "HealthyChildren (AAP) – Vitamin D for babies, children & adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/vitamin-d-on-the-double.aspx"
        },
        {
          "label": "Mayo Clinic – Vitamin A: side effects & dosage",
          "url": "https://www.mayoclinic.org/drugs-supplements/vitamin-a-oral-route-intramuscular-route/description/drg-80000155"
        },
        {
          "label": "Mayo Clinic – Multivitamins: Do young children need them?",
          "url": "https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/expert-answers/multivitamins/faq-20058310"
        },
        {
          "label": "Healthline – How to increase height: Is it possible?",
          "url": "https://www.healthline.com/health/how-to-increase-height"
        },
        {
          "label": "Mayo Clinic – Iron deficiency in children: Prevention tips for parents",
          "url": "https://www.mayoclinic.org/healthy-lifestyle/childrens-health/in-depth/iron-deficiency/art-20045634"
        },
        {
          "label": "WHO – Zinc supplementation and growth in children",
          "url": "https://www.who.int/tools/elena/bbc/zinc-stunting"
        },
        {
          "label": "Mayo Clinic Health System – Can kids safely use supplements?",
          "url": "https://www.mayoclinichealthsystem.org/hometown-health/speaking-of-health/is-it-safe-for-my-kid-to-take-supplements"
        },
        {
          "label": "Mayo Clinic News Network – Omega-3 supplements for children",
          "url": "https://newsnetwork.mayoclinic.org/discussion/mayo-clinic-q-and-a-omega-3-supplements-for-children-what-does-the-research-show/"
        },
        {
          "label": "NCCIH – Dietary supplements for children and teens",
          "url": "https://www.nccih.nih.gov/health/tips/things-to-know-about-dietary-supplements-for-children-and-teens"
        }
      ],
      "related": [
        "vitamins-and-minerals-for-healthy-child-growth",
        "protein-key-to-child-growth"
      ],
      "suggested": [
        "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
        "healthy-teen-nutrition-a-comprehensive-guide-for-parents"
      ],
      "approvedBy": "Dr. Hossein Lavasanifar",
      "titleGradientIndices": [
        0,
        3,
        5
      ]
    },
    "wordCount": 5291,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "Types of supplements related to growth",
        "id": "types-of-supplements-related-to-growth"
      },
      {
        "depth": 2,
        "value": "Tips for buying and using supplements",
        "id": "tips-for-buying-and-using-supplements"
      },
      {
        "depth": 2,
        "value": "Warnings and precautions",
        "id": "warnings-and-precautions"
      },
      {
        "depth": 2,
        "value": "Conclusion",
        "id": "conclusion"
      }
    ]
  },
  {
    "metadata": {
      "title": "مکمل‌های غذایی برای رشد؛ راهنمای جامع برای خانواده‌ها",
      "description": "در این مقاله، با نگاهی علمی و قابل‌فهم برای خانواده‌ها، انواع مکمل‌های غذایی مؤثر بر رشد کودکان و نوجوانان (ویتامین‌ها، مواد معدنی، پروتئین‌ها، امگا۳ و غیره)، نکات مهم در خرید و مصرف، و هشدارهای ایمنی را مرور می‌کنیم؛ با تأکید مداوم بر این‌که هر مکمل فقط با تجویز و زیر نظر پزشک باید مصرف شود.",
      "keywords": [
        "پزشکی کودکان",
        "تغذیه کودک",
        "مکمل رشد",
        "رشد کودک"
      ],
      "locale": "fa",
      "sharedSlug": "growth-supplements-guide-for-families",
      "id": 19,
      "slug": "مکمل‌های-غذایی-برای-رشد–راهنمای-جامع-برای-خانواده‌ها",
      "image": "/blogs/growth-supplements-guide-for-families/0.png",
      "author": "هومان خوش بین",
      "date": "2025-11-30T20:30:00.000Z",
      "category": "general-health",
      "tags": [
        "پزشکی_کودکان",
        "تغذیه_کودک",
        "مکمل_رشد",
        "رشد_کودک"
      ],
      "resources": [
        {
          "label": "HealthyChildren (AAP) – Vitamin supplements for children",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/Where-We-Stand-Vitamins.aspx"
        },
        {
          "label": "HealthyChildren (AAP) – Vitamin D for babies, children & adolescents",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/vitamin-d-on-the-double.aspx"
        },
        {
          "label": "Mayo Clinic – Vitamin A: side effects & dosage",
          "url": "https://www.mayoclinic.org/drugs-supplements/vitamin-a-oral-route-intramuscular-route/description/drg-80000155"
        },
        {
          "label": "Mayo Clinic – Multivitamins: Do young children need them?",
          "url": "https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/expert-answers/multivitamins/faq-20058310"
        },
        {
          "label": "Healthline – How to increase height: Is it possible?",
          "url": "https://www.healthline.com/health/how-to-increase-height"
        },
        {
          "label": "Mayo Clinic – Iron deficiency in children: Prevention tips for parents",
          "url": "https://www.mayoclinic.org/healthy-lifestyle/childrens-health/in-depth/iron-deficiency/art-20045634"
        },
        {
          "label": "WHO – Zinc supplementation and growth in children",
          "url": "https://www.who.int/tools/elena/bbc/zinc-stunting"
        },
        {
          "label": "Mayo Clinic Health System – Can kids safely use supplements?",
          "url": "https://www.mayoclinichealthsystem.org/hometown-health/speaking-of-health/is-it-safe-for-my-kid-to-take-supplements"
        },
        {
          "label": "Mayo Clinic News Network – Omega-3 supplements for children",
          "url": "https://newsnetwork.mayoclinic.org/discussion/mayo-clinic-q-and-a-omega-3-supplements-for-children-what-does-the-research-show/"
        },
        {
          "label": "NCCIH – Dietary supplements for children and teens",
          "url": "https://www.nccih.nih.gov/health/tips/things-to-know-about-dietary-supplements-for-children-and-teens"
        }
      ],
      "related": [
        "vitamins-and-minerals-for-healthy-child-growth",
        "protein-key-to-child-growth"
      ],
      "suggested": [
        "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
        "healthy-teen-nutrition-a-comprehensive-guide-for-parents"
      ],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0,
        3,
        5
      ]
    },
    "wordCount": 6014,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "انواع مکمل‌های مرتبط با رشد",
        "id": "انواع-مکملهای-مرتبط-با-رشد"
      },
      {
        "depth": 2,
        "value": "نکات خرید و مصرف مکمل‌ها",
        "id": "نکات-خرید-و-مصرف-مکملها"
      },
      {
        "depth": 2,
        "value": "هشدارها و موارد احتیاط",
        "id": "هشدارها-و-موارد-احتیاط"
      },
      {
        "depth": 2,
        "value": "نتیجه‌گیری",
        "id": "نتیجهگیری"
      }
    ]
  },
  {
    "metadata": {
      "title": "Gesunde Ernährung des Kindes; ein umfassender Leitfaden von der Geburt bis zum 5. Lebensjahr",
      "description": "Eine bedarfsgerechte Ernährung von der Geburt bis zum 5. Lebensjahr ist die Grundlage für eine gesunde körperliche und geistige Entwicklung des Kindes. In diesem Artikel finden Sie einen umfassenden, wissenschaftlich fundierten und praxisnahen Leitfaden zur Ernährung von Säuglingen, Kleinkindern und Vorschulkindern.",
      "keywords": [
        "Ernährung_Kind",
        "Ernährung_Säugling",
        "Ernährung_Kleinkind",
        "Ernährung_Vorschulkind",
        "optimales_Wachstum"
      ],
      "locale": "de",
      "sharedSlug": "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
      "id": 4,
      "slug": "gesunde-ernaehrung-kind-umfassender-leitfaden-von-geburt-bis-5-lebensjahr",
      "image": "/blogs/healthy-nutrition-for-children-complete-guide-from-birth-to-5-years/1.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-25T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "Kinderheilkunde",
        "Kinderernährung",
        "Kindesentwicklung",
        "gesunde_Ernährung"
      ],
      "resources": [
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "CDC – Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "NHS – Your baby’s first solid foods",
          "url": "https://www.nhs.uk/conditions/baby/weaning-and-feeding/babys-first-solid-foods/"
        },
        {
          "label": "NHS – Vitamins for children",
          "url": "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamins-for-children/"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasanifar",
      "titleGradientIndices": [
        0,
        1,
        2,
        3
      ]
    },
    "wordCount": 2236,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Ernährung im Säuglingsalter (0 bis 12 Monate)",
        "id": "ernährung-im-säuglingsalter-0-bis-12-monate"
      },
      {
        "depth": 2,
        "value": "Ernährung von Kleinkindern (1 bis 3 Jahre)",
        "id": "ernährung-von-kleinkindern-1-bis-3-jahre"
      },
      {
        "depth": 2,
        "value": "Ernährung von Vorschulkindern (3 bis 5 Jahre)",
        "id": "ernährung-von-vorschulkindern-3-bis-5-jahre"
      },
      {
        "depth": 2,
        "value": "Wichtige Sicherheitshinweise und allgemeine Empfehlungen",
        "id": "wichtige-sicherheitshinweise-und-allgemeine-empfehlungen"
      },
      {
        "depth": 2,
        "value": "Schlussfolgerung",
        "id": "schlussfolgerung"
      },
      {
        "depth": 2,
        "value": "Zusammenfassung der wichtigsten Punkte und Zahlen",
        "id": "zusammenfassung-der-wichtigsten-punkte-und-zahlen"
      }
    ]
  },
  {
    "metadata": {
      "title": "Healthy Nutrition for Children; A Complete Guide from Birth to 5 Years",
      "description": "Appropriate nutrition from birth to 5 years forms the foundation of healthy physical and mental development in children. This article provides a complete, evidence-based and practical guide to feeding infants, toddlers and preschoolers.",
      "keywords": [
        "child_nutrition",
        "infant_nutrition",
        "toddler_nutrition",
        "preschool_nutrition",
        "optimal_growth"
      ],
      "locale": "en",
      "sharedSlug": "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
      "id": 5,
      "slug": "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
      "image": "/blogs/healthy-nutrition-for-children-complete-guide-from-birth-to-5-years/1.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-25T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "pediatrics",
        "child_nutrition",
        "child_growth",
        "healthy_eating"
      ],
      "resources": [
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "CDC – Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "NHS – Your baby’s first solid foods",
          "url": "https://www.nhs.uk/conditions/baby/weaning-and-feeding/babys-first-solid-foods/"
        },
        {
          "label": "NHS – Vitamins for children",
          "url": "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamins-for-children/"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasanifar",
      "titleGradientIndices": [
        0,
        1,
        2,
        3
      ]
    },
    "wordCount": 2289,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "Nutrition in Infancy (0 to 12 Months)",
        "id": "nutrition-in-infancy-0-to-12-months"
      },
      {
        "depth": 2,
        "value": "Nutrition for Toddlers (1 to 3 Years)",
        "id": "nutrition-for-toddlers-1-to-3-years"
      },
      {
        "depth": 2,
        "value": "Nutrition for Preschoolers (3 to 5 Years)",
        "id": "nutrition-for-preschoolers-3-to-5-years"
      },
      {
        "depth": 2,
        "value": "Special Safety Tips and General Recommendations",
        "id": "special-safety-tips-and-general-recommendations"
      },
      {
        "depth": 2,
        "value": "Conclusion",
        "id": "conclusion"
      },
      {
        "depth": 2,
        "value": "Summary of Key Points and Numbers",
        "id": "summary-of-key-points-and-numbers"
      }
    ]
  },
  {
    "metadata": {
      "title": "تغذیه سالم کودک؛ راهنمای کامل از تولد تا ۵ سالگی",
      "description": "تغذیه مناسب از بدو تولد تا ۵ سالگی، پایهٔ رشد سالم جسمی و ذهنی کودک است. در این مقاله، یک راهنمای کامل، علمی و کاربردی برای تغذیه نوزاد، نوپا و کودک پیش‌دبستانی ارائه می‌شود.",
      "keywords": [
        "تغذیه_کودک",
        "تغذیه_نوزاد",
        "تغذیه_نوپا",
        "تغذیه_پیش‌دبستانی",
        "رشد_بهینه"
      ],
      "locale": "fa",
      "sharedSlug": "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years",
      "id": 6,
      "slug": "تغذیه-سالم-کودک-راهنمای-کامل-از-تولد-تا-۵-سالگی",
      "image": "/blogs/healthy-nutrition-for-children-complete-guide-from-birth-to-5-years/1.png",
      "author": "هومان خوش بین",
      "date": "2025-11-25T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "پزشکی_کودکان",
        "تغذیه_کودک",
        "رشد_کودک",
        "تغذیه_سالم"
      ],
      "resources": [
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "CDC – Infant and Toddler Nutrition",
          "url": "https://www.cdc.gov/nutrition/infantandtoddlernutrition/index.html"
        },
        {
          "label": "NHS – Your baby’s first solid foods",
          "url": "https://www.nhs.uk/conditions/baby/weaning-and-feeding/babys-first-solid-foods/"
        },
        {
          "label": "NHS – Vitamins for children",
          "url": "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamins-for-children/"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 2562,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "تغذیه در نوزادی (۰ تا ۱۲ ماهگی)",
        "id": "تغذیه-در-نوزادی-۰-تا-۱۲-ماهگی"
      },
      {
        "depth": 2,
        "value": "تغذیه کودک نوپا (۱ تا ۳ سال)",
        "id": "تغذیه-کودک-نوپا-۱-تا-۳-سال"
      },
      {
        "depth": 2,
        "value": "تغذیه کودکان پیش‌دبستانی (۳ تا ۵ سال)",
        "id": "تغذیه-کودکان-پیشدبستانی-۳-تا-۵-سال"
      },
      {
        "depth": 2,
        "value": "نکات ویژهٔ ایمنی و توصیه‌های کلی",
        "id": "نکات-ویژهٔ-ایمنی-و-توصیههای-کلی"
      },
      {
        "depth": 2,
        "value": "نتیجه‌گیری",
        "id": "نتیجهگیری"
      },
      {
        "depth": 2,
        "value": "خلاصه نکات کلیدی و اعداد مهم",
        "id": "خلاصه-نکات-کلیدی-و-اعداد-مهم"
      }
    ]
  },
  {
    "metadata": {
      "title": "Gesunde Ernährung für Jugendliche; Ein umfassender Leitfaden für Eltern",
      "description": "Eine ausgewogene Ernährung im Alter von 6 bis 15 Jahren spielt eine entscheidende Rolle für das Größenwachstum, die Knochengesundheit, die Gehirnentwicklung und die Vorbeugung von Übergewicht oder Untergewicht. In diesem Artikel wird ein vollständiger, wissenschaftlicher und praxisnaher Leitfaden für die gesunde Ernährung von Schulkindern und Jugendlichen vorgestellt.",
      "keywords": [
        "jugendliche ernaehrung",
        "schulkinder ernaehrung",
        "gesunde ernaehrung",
        "jugend wachstum",
        "ernaehrung 6bis15"
      ],
      "locale": "de",
      "sharedSlug": "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
      "id": 7,
      "slug": "gesunde-ernaehrung-jugendliche-umfassender-elternratgeber",
      "image": "/blogs/healthy-teen-nutrition-a-comprehensive-guide-for-parents/0.jpeg",
      "author": "Hooman Khoshbin",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "kinderheilkunde",
        "ernaehrung_jugendliche",
        "jugend_wachstum",
        "gesunde_ernaehrung"
      ],
      "resources": [
        {
          "label": "WHO – Gesunde Ernährung",
          "url": "https://www.who.int/news-room/fact-sheets/detail/healthy-diet"
        },
        {
          "label": "WHO – Gesundheit und Ernährung von Jugendlichen",
          "url": "https://www.who.int/health-topics/adolescent-health"
        },
        {
          "label": "CDC – Vorteile gesunder Ernährung für Kinder",
          "url": "https://www.cdc.gov/nutrition/features/benefits-of-healthy-eating-for-children.html"
        },
        {
          "label": "NIH – Amt für Nahrungsergänzungsmittel",
          "url": "https://ods.od.nih.gov"
        },
        {
          "label": "AAP – Ernährungsbedürfnisse von Teenagern",
          "url": "https://www.healthychildren.org/English/ages-stages/teen/nutrition/Pages/A-Teenagers-Nutritional-Needs.aspx"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 3198,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Die Rolle der Ernährung für Wachstum, Gehirn, Knochen und gesundes Gewicht",
        "id": "die-rolle-der-ernährung-für-wachstum-gehirn-knochen-und-gesundes-gewicht"
      },
      {
        "depth": 2,
        "value": "Ernährungsbedürfnisse von Kindern im Alter von 6–9 Jahren",
        "id": "ernährungsbedürfnisse-von-kindern-im-alter-von-69-jahren"
      },
      {
        "depth": 2,
        "value": "Ernährungsbedürfnisse von Kindern im Alter von 10–12 Jahren",
        "id": "ernährungsbedürfnisse-von-kindern-im-alter-von-1012-jahren"
      },
      {
        "depth": 2,
        "value": "Ernährungsbedürfnisse von Jugendlichen im Alter von 13–15 Jahren",
        "id": "ernährungsbedürfnisse-von-jugendlichen-im-alter-von-1315-jahren"
      },
      {
        "depth": 2,
        "value": "Häufige Irrtümer über die Ernährung von Jugendlichen",
        "id": "häufige-irrtümer-über-die-ernährung-von-jugendlichen"
      },
      {
        "depth": 2,
        "value": "Fazit und abschließende Empfehlungen",
        "id": "fazit-und-abschließende-empfehlungen"
      }
    ]
  },
  {
    "metadata": {
      "title": "Healthy Teen Nutrition; A Comprehensive Guide for Parents",
      "description": "Proper nutrition during ages 6 to 15 plays an essential role in height growth, bone health, brain development, and preventing obesity or underweight. In this article, a complete, scientific, and practical guide to healthy eating for school-age children and teenagers is provided.",
      "keywords": [
        "teen_nutrition",
        "school_children_nutrition",
        "healthy_diet",
        "teen_growth",
        "nutrition_6to15"
      ],
      "locale": "en",
      "sharedSlug": "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
      "id": 8,
      "slug": "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
      "image": "/blogs/healthy-teen-nutrition-a-comprehensive-guide-for-parents/0.jpeg",
      "author": "Hooman Khoshbin",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "pediatrics",
        "teen_nutrition",
        "teen_growth",
        "healthy_diet"
      ],
      "resources": [
        {
          "label": "WHO – Healthy diet",
          "url": "https://www.who.int/news-room/fact-sheets/detail/healthy-diet"
        },
        {
          "label": "WHO – Adolescent health and nutrition",
          "url": "https://www.who.int/health-topics/adolescent-health"
        },
        {
          "label": "CDC – Benefits of Healthy Eating for Children",
          "url": "https://www.cdc.gov/nutrition/features/benefits-of-healthy-eating-for-children.html"
        },
        {
          "label": "NIH – Office of Dietary Supplements",
          "url": "https://ods.od.nih.gov"
        },
        {
          "label": "AAP – A Teenager’s Nutritional Needs",
          "url": "https://www.healthychildren.org/English/ages-stages/teen/nutrition/Pages/A-Teenagers-Nutritional-Needs.aspx"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 3528,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "The role of nutrition in growth, brain development, bone health, and healthy weight",
        "id": "the-role-of-nutrition-in-growth-brain-development-bone-health-and-healthy-weight"
      },
      {
        "depth": 2,
        "value": "Nutritional needs of children aged 6–9 years",
        "id": "nutritional-needs-of-children-aged-69-years"
      },
      {
        "depth": 2,
        "value": "Nutritional needs of children aged 10–12 years",
        "id": "nutritional-needs-of-children-aged-1012-years"
      },
      {
        "depth": 2,
        "value": "Nutritional needs of teenagers aged 13–15 years",
        "id": "nutritional-needs-of-teenagers-aged-1315-years"
      },
      {
        "depth": 2,
        "value": "Common myths about teen nutrition",
        "id": "common-myths-about-teen-nutrition"
      },
      {
        "depth": 2,
        "value": "Conclusion and final recommendations",
        "id": "conclusion-and-final-recommendations"
      }
    ]
  },
  {
    "metadata": {
      "title": "تغذیه سالم نوجوانان؛ راهنمای جامع برای والدین",
      "description": "تغذیه مناسب در سال‌های ۶ تا ۱۵ سالگی، نقش مهمی در رشد قد، سلامت استخوان‌ها، تکامل مغز و پیشگیری از چاقی یا کم‌وزنی دارد. در این مقاله، یک راهنمای کامل، علمی و کاربردی برای تغذیه سالم کودکان دبستانی و نوجوانان ارائه می‌شود.",
      "keywords": [
        "تغذیه نوجوان",
        "تغذیه کودکان مدرسه",
        "تغذیه سالم",
        "رشد نوجوان",
        "تغذیه ۶تا۱۵سال"
      ],
      "locale": "fa",
      "sharedSlug": "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
      "id": 9,
      "slug": "تغذیه-سالم-نوجوانان-راهنمای-جامع-برای-والدین",
      "image": "/blogs/healthy-teen-nutrition-a-comprehensive-guide-for-parents/0.jpeg",
      "author": "هومان خوش بین",
      "date": "2025-11-26T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "پزشکی_کودکان",
        "تغذیه_نوجوان",
        "رشد_نوجوان",
        "تغذیه_سالم"
      ],
      "resources": [
        {
          "label": "WHO – Healthy diet",
          "url": "https://www.who.int/news-room/fact-sheets/detail/healthy-diet"
        },
        {
          "label": "WHO – Adolescent health and nutrition",
          "url": "https://www.who.int/health-topics/adolescent-health"
        },
        {
          "label": "CDC – Benefits of Healthy Eating for Children",
          "url": "https://www.cdc.gov/nutrition/features/benefits-of-healthy-eating-for-children.html"
        },
        {
          "label": "NIH – Office of Dietary Supplements",
          "url": "https://ods.od.nih.gov"
        },
        {
          "label": "AAP – A Teenager’s Nutritional Needs",
          "url": "https://www.healthychildren.org/English/ages-stages/teen/nutrition/Pages/A-Teenagers-Nutritional-Needs.aspx"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0,
        1,
        2
      ]
    },
    "wordCount": 3888,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "نقش تغذیه در رشد، تکامل مغز، استخوان‌ها و وزن سالم",
        "id": "نقش-تغذیه-در-رشد-تکامل-مغز-استخوانها-و-وزن-سالم"
      },
      {
        "depth": 2,
        "value": "نیازهای تغذیه‌ای کودکان ۶–۹ سال",
        "id": "نیازهای-تغذیهای-کودکان-۶۹-سال"
      },
      {
        "depth": 2,
        "value": "نیازهای تغذیه‌ای کودکان ۱۰–۱۲ سال",
        "id": "نیازهای-تغذیهای-کودکان-۱۰۱۲-سال"
      },
      {
        "depth": 2,
        "value": "نیازهای تغذیه‌ای نوجوانان ۱۳–۱۵ سال",
        "id": "نیازهای-تغذیهای-نوجوانان-۱۳۱۵-سال"
      },
      {
        "depth": 2,
        "value": "باورهای نادرست رایج درباره تغذیه نوجوانان",
        "id": "باورهای-نادرست-رایج-درباره-تغذیه-نوجوانان"
      },
      {
        "depth": 2,
        "value": "جمع‌بندی و توصیه پایانی",
        "id": "جمعبندی-و-توصیه-پایانی"
      }
    ]
  },
  {
    "metadata": {
      "title": "Die Bedeutung der Kinderimpfungen",
      "description": "Kinderimpfungen gehören zu den wirksamsten Maßnahmen der öffentlichen Gesundheit. In diesem Artikel erfahren Sie mehr über die Rolle von Impfstoffen bei der Krankheitsprävention, ihre Sicherheit und die Empfehlungen internationaler Organisationen.",
      "keywords": [
        "kinderimpfung",
        "immunisierung",
        "kindergesundheit",
        "prävention"
      ],
      "locale": "de",
      "sharedSlug": "importance-of-childhood-vaccination",
      "id": 10,
      "slug": "bedeutung-der-kinderimpfungen",
      "image": "/blogs/importance-of-childhood-vaccination/1.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-14T00:00:00.000Z",
      "category": "general-health",
      "tags": [
        "pädiatrie",
        "impfung",
        "öffentliche_gesundheit"
      ],
      "resources": [
        {
          "label": "UNICEF - Why vaccines matter for children",
          "url": "https://www.unicef.org/stories/why-vaccines-matter-children#:~:text=Vaccines%20are%20one%20of%20the,ensuring%20healthier%20futures%20for%20generations"
        },
        {
          "label": "WHO - Vaccines and immunization",
          "url": "https://www.who.int/health-topics/vaccines-and-immunization#tab=tab_1"
        },
        {
          "label": "CDC - Reasons to Vaccinate",
          "url": "https://www.cdc.gov/vaccines-children/reasons/index.html#:~:text=Immunity%20is%20the%20body%E2%80%99s%20way,build%20up%20their%20natural%20defenses"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasanifar",
      "titleGradientIndices": [
        2
      ]
    },
    "wordCount": 524,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Was ist eine Impfung und wie funktioniert sie?",
        "id": "was-ist-eine-impfung-und-wie-funktioniert-sie"
      },
      {
        "depth": 2,
        "value": "Warum Impfstoffe für Kinder unverzichtbar sind",
        "id": "warum-impfstoffe-für-kinder-unverzichtbar-sind"
      },
      {
        "depth": 2,
        "value": "Sicherheit von Impfstoffen",
        "id": "sicherheit-von-impfstoffen"
      },
      {
        "depth": 2,
        "value": "Empfehlungen internationaler Organisationen",
        "id": "empfehlungen-internationaler-organisationen"
      },
      {
        "depth": 2,
        "value": "Fazit",
        "id": "fazit"
      },
      {
        "depth": 2,
        "value": "Wichtige Kernpunkte",
        "id": "wichtige-kernpunkte"
      }
    ]
  },
  {
    "metadata": {
      "title": "Importance of Childhood Vaccination",
      "description": "Childhood vaccination is one of the most effective public health interventions. In this article, you will learn about the role of vaccines in disease prevention, their safety, and recommendations from international organizations.",
      "keywords": [
        "childhood_vaccination",
        "immunization",
        "child_health",
        "prevention"
      ],
      "locale": "en",
      "sharedSlug": "importance-of-childhood-vaccination",
      "id": 11,
      "slug": "importance-of-childhood-vaccination",
      "image": "/blogs/importance-of-childhood-vaccination/1.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-14T00:00:00.000Z",
      "category": "general-health",
      "tags": [
        "pediatrics",
        "vaccination",
        "public_health"
      ],
      "resources": [
        {
          "label": "UNICEF - Why vaccines matter for children",
          "url": "https://www.unicef.org/stories/why-vaccines-matter-children#:~:text=Vaccines%20are%20one%20of%20the,ensuring%20healthier%20futures%20for%20generations"
        },
        {
          "label": "WHO - Vaccines and immunization",
          "url": "https://www.who.int/health-topics/vaccines-and-immunization#tab=tab_1"
        },
        {
          "label": "CDC - Reasons to Vaccinate",
          "url": "https://www.cdc.gov/vaccines-children/reasons/index.html#:~:text=Immunity%20is%20the%20body%E2%80%99s%20way,build%20up%20their%20natural%20defenses"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "Dr. Hossein Lavasanifar",
      "titleGradientIndices": [
        2
      ]
    },
    "wordCount": 831,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "What is vaccination and how does it work?",
        "id": "what-is-vaccination-and-how-does-it-work"
      },
      {
        "depth": 2,
        "value": "Why are vaccines essential for children?",
        "id": "why-are-vaccines-essential-for-children"
      },
      {
        "depth": 2,
        "value": "Vaccine safety",
        "id": "vaccine-safety"
      },
      {
        "depth": 2,
        "value": "Recommendations from leading international organizations",
        "id": "recommendations-from-leading-international-organizations"
      },
      {
        "depth": 2,
        "value": "Conclusion",
        "id": "conclusion"
      },
      {
        "depth": 2,
        "value": "Key Takeaways",
        "id": "key-takeaways"
      }
    ]
  },
  {
    "metadata": {
      "title": "اهمیت واکسیناسیون کودکان",
      "description": "واکسیناسیون کودکان یکی از مؤثرترین مداخلات سلامت عمومی است. در این مقاله با نقش واکسن‌ها در پیشگیری از بیماری‌ها، ایمنی آن‌ها و توصیه‌های سازمان‌های بین‌المللی آشنا می‌شوید.",
      "keywords": [
        "واکسیناسیون_کودکان",
        "ایمن‌سازی",
        "سلامت_کودک",
        "پیشگیری"
      ],
      "locale": "fa",
      "sharedSlug": "importance-of-childhood-vaccination",
      "id": 12,
      "slug": "اهمیت-واکسیناسیون-کودکان",
      "image": "/blogs/importance-of-childhood-vaccination/1.png",
      "author": "هومان خوش بین",
      "date": "2025-11-14T00:00:00.000Z",
      "category": "general-health",
      "tags": [
        "پزشکی_کودکان",
        "واکسیناسیون",
        "سلامت_عمومی"
      ],
      "resources": [
        {
          "label": "UNICEF - Why vaccines matter for children",
          "url": "https://www.unicef.org/stories/why-vaccines-matter-children#:~:text=Vaccines%20are%20one%20of%20the,ensuring%20healthier%20futures%20for%20generations"
        },
        {
          "label": "WHO - Vaccines and immunization",
          "url": "https://www.who.int/health-topics/vaccines-and-immunization#tab=tab_1"
        },
        {
          "label": "CDC - Reasons to Vaccinate",
          "url": "https://www.cdc.gov/vaccines-children/reasons/index.html#:~:text=Immunity%20is%20the%20body%E2%80%99s%20way,build%20up%20their%20natural%20defenses"
        }
      ],
      "related": [],
      "suggested": [],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        2
      ]
    },
    "wordCount": 1714,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "واکسیناسیون چیست و چگونه عمل می‌کند؟",
        "id": "واکسیناسیون-چیست-و-چگونه-عمل-میکند"
      },
      {
        "depth": 2,
        "value": "چرا واکسن‌ها برای کودکان ضروری هستند؟",
        "id": "چرا-واکسنها-برای-کودکان-ضروری-هستند"
      },
      {
        "depth": 2,
        "value": "ایمنی و بی‌خطر بودن واکسن‌ها",
        "id": "ایمنی-و-بیخطر-بودن-واکسنها"
      },
      {
        "depth": 2,
        "value": "توصیه سازمان‌های معتبر بین‌المللی",
        "id": "توصیه-سازمانهای-معتبر-بینالمللی"
      },
      {
        "depth": 2,
        "value": "نتیجه‌گیری",
        "id": "نتیجهگیری"
      },
      {
        "depth": 2,
        "value": "خلاصه نکات کلیدی",
        "id": "خلاصه-نکات-کلیدی"
      }
    ]
  },
  {
    "metadata": {
      "title": "Protein: Der Schlüssel zum Größenwachstum Ihres Kindes",
      "description": "Protein ist eines der wichtigsten Nährstoffe für das Wachstum der Körpergröße, die Muskulatur, das Gehirn und das Immunsystem eines Kindes. In diesem Artikel erklären wir – in verständlicher Sprache und basierend auf zuverlässigen internationalen Quellen – alles über Menge, Art und Zeitpunkt der Proteinzufuhr vom Säuglingsalter bis zum Ende der Jugend.",
      "keywords": [
        "Protein Kind",
        "Wachstum Kind",
        "Größenwachstum",
        "Ernährung Kind",
        "Ernährung Jugendlicher",
        "Protein"
      ],
      "locale": "de",
      "sharedSlug": "protein-key-to-child-growth",
      "id": 15,
      "slug": "protein-der-schluessel-zum-wachstum-des-kindes",
      "image": "/blogs/protein-key-to-child-growth/0.jpeg",
      "author": "Houman Khoshbin",
      "date": "2025-11-29T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "Kinderernährung",
        "Wachstum_Kind",
        "Protein",
        "gesunde_Ernährung"
      ],
      "resources": [
        {
          "label": "WHO – Mangelernährung",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "WHO – Säuglings- und Kleinkinderernährung",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "CDC – Ernährung für Kinder & Jugendliche",
          "url": "https://www.cdc.gov/nutrition/childhood/index.html"
        },
        {
          "label": "American Academy of Pediatrics – Ernährung",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/default.aspx"
        },
        {
          "label": "Cleveland Clinic – Protein für Kinder",
          "url": "https://health.clevelandclinic.org"
        },
        {
          "label": "Children’s Health – Protein und Wachstum",
          "url": "https://www.childrens.com"
        }
      ],
      "related": [
        "vitamins-and-minerals-for-healthy-child-growth",
        "growth-supplements-guide-for-families"
      ],
      "suggested": [
        "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
        "common-child-nutrition-mistakes-from-infancy-to-adolescence"
      ],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0
      ]
    },
    "wordCount": 1253,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung: Warum ist Protein für das Wachstum eines Kindes so wichtig?",
        "id": "einleitung-warum-ist-protein-für-das-wachstum-eines-kindes-so-wichtig"
      },
      {
        "depth": 2,
        "value": "Protein und seine Aufgaben im Körper eines Kindes",
        "id": "protein-und-seine-aufgaben-im-körper-eines-kindes"
      },
      {
        "depth": 2,
        "value": "Wie viel Protein braucht mein Kind pro Tag?",
        "id": "wie-viel-protein-braucht-mein-kind-pro-tag"
      },
      {
        "depth": 2,
        "value": "Die besten Proteinquellen für jedes Alter: Von Muttermilch bis Familienkost",
        "id": "die-besten-proteinquellen-für-jedes-alter-von-muttermilch-bis-familienkost"
      },
      {
        "depth": 2,
        "value": "Wann sollte ein Kind Protein essen? Die Bedeutung der Verteilung",
        "id": "wann-sollte-ein-kind-protein-essen-die-bedeutung-der-verteilung"
      },
      {
        "depth": 2,
        "value": "Protein und das Wachstum von Muskeln, Gehirn und Immunsystem",
        "id": "protein-und-das-wachstum-von-muskeln-gehirn-und-immunsystem"
      },
      {
        "depth": 2,
        "value": "Häufige Fehler von Eltern beim Thema Protein",
        "id": "häufige-fehler-von-eltern-beim-thema-protein"
      },
      {
        "depth": 2,
        "value": "Kinder mit Wachstumsproblemen: Brauchen sie mehr Protein?",
        "id": "kinder-mit-wachstumsproblemen-brauchen-sie-mehr-protein"
      },
      {
        "depth": 2,
        "value": "Zusammenfassung: Protein – ein wichtiges Puzzleteil der gesunden Ernährung",
        "id": "zusammenfassung-protein--ein-wichtiges-puzzleteil-der-gesunden-ernährung"
      }
    ]
  },
  {
    "metadata": {
      "title": "Protein: The Key to Your Child's Height Growth",
      "description": "Protein is one of the most essential nutrients for a child’s height growth, muscles, brain, and immune system. In this article, written in simple language and supported by reputable global sources, we review everything about the amount, type, and timing of protein intake from infancy to late adolescence.",
      "keywords": [
        "child protein",
        "child growth",
        "height growth",
        "child nutrition",
        "teen nutrition",
        "protein"
      ],
      "locale": "en",
      "sharedSlug": "protein-key-to-child-growth",
      "id": 14,
      "slug": "protein-key-to-child-growth",
      "image": "/blogs/protein-key-to-child-growth/0.jpeg",
      "author": "Houman Khoshbin",
      "date": "2025-11-29T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "child_nutrition",
        "child_growth",
        "protein",
        "healthy_eating"
      ],
      "resources": [
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "CDC – Child & Teen Nutrition",
          "url": "https://www.cdc.gov/nutrition/childhood/index.html"
        },
        {
          "label": "American Academy of Pediatrics – Nutrition",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/default.aspx"
        },
        {
          "label": "Cleveland Clinic – Protein for kids",
          "url": "https://health.clevelandclinic.org"
        },
        {
          "label": "Children’s Health – Protein and child growth",
          "url": "https://www.childrens.com"
        }
      ],
      "related": [
        "vitamins-and-minerals-for-healthy-child-growth",
        "growth-supplements-guide-for-families"
      ],
      "suggested": [
        "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
        "common-child-nutrition-mistakes-from-infancy-to-adolescence"
      ],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0
      ]
    },
    "wordCount": 1570,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction: Why is protein so important for your child’s growth?",
        "id": "introduction-why-is-protein-so-important-for-your-childs-growth"
      },
      {
        "depth": 2,
        "value": "Protein and its roles in a child’s body",
        "id": "protein-and-its-roles-in-a-childs-body"
      },
      {
        "depth": 2,
        "value": "How much protein does my child need per day?",
        "id": "how-much-protein-does-my-child-need-per-day"
      },
      {
        "depth": 2,
        "value": "Best protein sources at each age: from breast milk to family meals",
        "id": "best-protein-sources-at-each-age-from-breast-milk-to-family-meals"
      },
      {
        "depth": 2,
        "value": "When should kids eat protein? The importance of distribution",
        "id": "when-should-kids-eat-protein-the-importance-of-distribution"
      },
      {
        "depth": 2,
        "value": "Protein and growth of muscles, brain, and immunity",
        "id": "protein-and-growth-of-muscles-brain-and-immunity"
      },
      {
        "depth": 2,
        "value": "Common mistakes parents make about protein",
        "id": "common-mistakes-parents-make-about-protein"
      },
      {
        "depth": 2,
        "value": "Children with growth problems: Do they need more protein?",
        "id": "children-with-growth-problems-do-they-need-more-protein"
      },
      {
        "depth": 2,
        "value": "Summary: Protein—one piece of the healthy nutrition puzzle",
        "id": "summary-proteinone-piece-of-the-healthy-nutrition-puzzle"
      }
    ]
  },
  {
    "metadata": {
      "title": "پروتئین؛ کلید رشد قد کودک",
      "description": "پروتئین یکی از کلیدی‌ترین مواد مغذی برای رشد قد، عضلات، مغز و سیستم ایمنی کودک است. در این مقاله، به زبان ساده و با تکیه بر منابع معتبر جهانی، همه چیز درباره مقدار، نوع و زمان مصرف پروتئین از نوزادی تا پایان نوجوانی را بررسی می‌کنیم.",
      "keywords": [
        "پروتئین کودک",
        "رشد کودک",
        "رشد قد",
        "تغذیه کودک",
        "تغذیه نوجوان",
        "پروتئین"
      ],
      "locale": "fa",
      "sharedSlug": "protein-key-to-child-growth",
      "id": 13,
      "slug": "پروتئین-کلید-رشد-قد-کودک",
      "image": "/blogs/protein-key-to-child-growth/0.jpeg",
      "author": "هومان خوش بین",
      "date": "2025-11-29T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "تغذیه_کودک",
        "رشد_کودک",
        "پروتئین",
        "تغذیه_سالم"
      ],
      "resources": [
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "WHO – Infant and young child feeding",
          "url": "https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding"
        },
        {
          "label": "CDC – Child & Teen Nutrition",
          "url": "https://www.cdc.gov/nutrition/childhood/index.html"
        },
        {
          "label": "American Academy of Pediatrics – Nutrition",
          "url": "https://www.healthychildren.org/English/healthy-living/nutrition/Pages/default.aspx"
        },
        {
          "label": "Cleveland Clinic – Protein for kids",
          "url": "https://health.clevelandclinic.org"
        },
        {
          "label": "Children’s Health – Protein and child growth",
          "url": "https://www.childrens.com"
        }
      ],
      "related": [
        "vitamins-and-minerals-for-healthy-child-growth",
        "growth-supplements-guide-for-families"
      ],
      "suggested": [
        "healthy-teen-nutrition-a-comprehensive-guide-for-parents",
        "common-child-nutrition-mistakes-from-infancy-to-adolescence"
      ],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0
      ]
    },
    "wordCount": 4253,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه: چرا پروتئین برای رشد کودک این‌قدر مهم است؟",
        "id": "مقدمه-چرا-پروتئین-برای-رشد-کودک-اینقدر-مهم-است"
      },
      {
        "depth": 2,
        "value": "پروتئین و نقش‌های آن در بدن کودک",
        "id": "پروتئین-و-نقشهای-آن-در-بدن-کودک"
      },
      {
        "depth": 2,
        "value": "کودک من به چقدر پروتئین در روز نیاز دارد؟",
        "id": "کودک-من-به-چقدر-پروتئین-در-روز-نیاز-دارد"
      },
      {
        "depth": 2,
        "value": "بهترین منابع پروتئین برای هر سن: از شیر مادر تا غذای خانوادگی",
        "id": "بهترین-منابع-پروتئین-برای-هر-سن-از-شیر-مادر-تا-غذای-خانوادگی"
      },
      {
        "depth": 2,
        "value": "چه زمانی پروتئین بخورد؟ اهمیت توزیع در طول روز",
        "id": "چه-زمانی-پروتئین-بخورد-اهمیت-توزیع-در-طول-روز"
      },
      {
        "depth": 2,
        "value": "پروتئین و رشد عضلات، مغز و سیستم ایمنی",
        "id": "پروتئین-و-رشد-عضلات-مغز-و-سیستم-ایمنی"
      },
      {
        "depth": 2,
        "value": "اشتباهات رایج والدین دربارهٔ پروتئین",
        "id": "اشتباهات-رایج-والدین-دربارهٔ-پروتئین"
      },
      {
        "depth": 2,
        "value": "کودکان با مشکلات رشد: آیا به پروتئین بیشتری نیاز دارند؟",
        "id": "کودکان-با-مشکلات-رشد-آیا-به-پروتئین-بیشتری-نیاز-دارند"
      },
      {
        "depth": 2,
        "value": "جمع‌بندی: پروتئین، یکی از قطعات پازل تغذیهٔ سالم",
        "id": "جمعبندی-پروتئین-یکی-از-قطعات-پازل-تغذیهٔ-سالم"
      }
    ]
  },
  {
    "metadata": {
      "title": "Großes Wachstum und gesunde Entwicklung: Die Rolle der Vitamine bei Kindern",
      "description": "Für das Größenwachstum, starke Knochen und ein gesundes Immunsystem braucht Ihr Kind die richtige Kombination aus Vitaminen und Mineralstoffen. In diesem Artikel besprechen wir wissenschaftlich fundiert und zugleich einfach und praxisnah die wichtigsten Vitamine und Mineralstoffe für das Wachstum von Kindern, ihre Nahrungsquellen und praktische Tipps für Eltern.",
      "keywords": [
        "vitamine_kind",
        "wachstum_koerpergroesse",
        "mineralstoffe",
        "kindernaehrung",
        "gesundes_wachstum"
      ],
      "locale": "de",
      "sharedSlug": "vitamins-and-minerals-for-healthy-child-growth",
      "id": 17,
      "slug": "grosses-wachstum-und-gesunde-entwicklung-rolle-der-vitamine-bei-kindern",
      "image": "/blogs/vitamins-and-minerals-for-healthy-child-growth/0.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-30T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "kinderheilkunde",
        "kindernaehrung",
        "kindeswachstum",
        "vitamine",
        "mineralstoffe"
      ],
      "resources": [
        {
          "label": "WHO – Micronutrient deficiencies",
          "url": "https://www.who.int/health-topics/micronutrients"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "CDC – Micronutrients",
          "url": "https://www.cdc.gov/nutrition/micronutrients"
        },
        {
          "label": "NHS – Vitamins for children",
          "url": "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamins-for-children/"
        },
        {
          "label": "NIH – Office of Dietary Supplements",
          "url": "https://ods.od.nih.gov/factsheets/list-all/"
        },
        {
          "label": "Vitamins & minerals for kids & teens",
          "url": "https://raisingchildren.net.au/teens/healthy-lifestyle/nutrients/vitamins-minerals"
        },
        {
          "label": "Does My Child Need a Supplement? – Academy of Nutrition and Dietetics",
          "url": "https://www.eatright.org/health/essential-nutrients/supplements/does-my-child-need-a-supplement"
        },
        {
          "label": "Children – Micronutrient Needs | Linus Pauling Institute",
          "url": "https://lpi.oregonstate.edu/mic/life-stages/children"
        },
        {
          "label": "Nutrients for Toddlers – Boys Town Pediatrics",
          "url": "https://www.boystownpediatrics.org/knowledge-center/toddler-nutrition"
        },
        {
          "label": "Vitamin D | Infant and Toddler Nutrition – CDC",
          "url": "https://www.cdc.gov/infant-toddler-nutrition/vitamins-minerals/vitamin-d.html"
        },
        {
          "label": "Iron | Infant and Toddler Nutrition – CDC",
          "url": "https://www.cdc.gov/infant-toddler-nutrition/vitamins-minerals/iron.html"
        },
        {
          "label": "Where We Stand: Vitamin D & Iron Supplements for Babies – HealthyChildren.org",
          "url": "https://www.healthychildren.org/English/ages-stages/baby/feeding-nutrition/Pages/Vitamin-Iron-Supplements.aspx"
        }
      ],
      "related": [
        "growth-supplements-guide-for-families",
        "protein-key-to-child-growth"
      ],
      "suggested": [
        "common-child-nutrition-mistakes-from-infancy-to-adolescence",
        "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years"
      ],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        3,
        6
      ]
    },
    "wordCount": 2887,
    "toc": [
      {
        "depth": 2,
        "value": "Einleitung",
        "id": "einleitung"
      },
      {
        "depth": 2,
        "value": "Vitamine und Mineralstoffe – die versteckten Motoren des kindlichen Wachstums",
        "id": "vitamine-und-mineralstoffe--die-versteckten-motoren-des-kindlichen-wachstums"
      },
      {
        "depth": 2,
        "value": "Teil 1: Wichtige Vitamine für das Wachstum von Kindern",
        "id": "teil-1-wichtige-vitamine-für-das-wachstum-von-kindern"
      },
      {
        "depth": 2,
        "value": "Teil 2: Wichtige Mineralstoffe für das Wachstum von Kindern",
        "id": "teil-2-wichtige-mineralstoffe-für-das-wachstum-von-kindern"
      },
      {
        "depth": 2,
        "value": "Teil 3: Nahrungsergänzungsmittel – natürliche Lebensmittel haben Vorrang",
        "id": "teil-3-nahrungsergänzungsmittel--natürliche-lebensmittel-haben-vorrang"
      },
      {
        "depth": 2,
        "value": "Teil 4: Praktische Tipps für Eltern",
        "id": "teil-4-praktische-tipps-für-eltern"
      },
      {
        "depth": 2,
        "value": "Fazit",
        "id": "fazit"
      }
    ]
  },
  {
    "metadata": {
      "title": "Tall Growth and Healthy Development: The Role of Vitamins in Children",
      "description": "For height growth, strong bones, and a healthy immune system, your child needs the right combination of vitamins and minerals. In this article, we review—scientifically yet simply and practically—the key vitamins and minerals for child growth, their food sources, and practical tips for parents.",
      "keywords": [
        "child_vitamins",
        "height_growth",
        "minerals",
        "child_nutrition",
        "healthy_growth"
      ],
      "locale": "en",
      "sharedSlug": "vitamins-and-minerals-for-healthy-child-growth",
      "id": 18,
      "slug": "tall-growth-and-healthy-development-role-of-vitamins-in-children",
      "image": "/blogs/vitamins-and-minerals-for-healthy-child-growth/0.png",
      "author": "Hooman Khoshbin",
      "date": "2025-11-30T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "pediatrics",
        "child_nutrition",
        "child_growth",
        "vitamins",
        "minerals"
      ],
      "resources": [
        {
          "label": "WHO – Micronutrient deficiencies",
          "url": "https://www.who.int/health-topics/micronutrients"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "CDC – Micronutrients",
          "url": "https://www.cdc.gov/nutrition/micronutrients"
        },
        {
          "label": "NHS – Vitamins for children",
          "url": "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamins-for-children/"
        },
        {
          "label": "NIH – Office of Dietary Supplements",
          "url": "https://ods.od.nih.gov/factsheets/list-all/"
        },
        {
          "label": "Vitamins & minerals for kids & teens",
          "url": "https://raisingchildren.net.au/teens/healthy-lifestyle/nutrients/vitamins-minerals"
        },
        {
          "label": "Does My Child Need a Supplement? – Academy of Nutrition and Dietetics",
          "url": "https://www.eatright.org/health/essential-nutrients/supplements/does-my-child-need-a-supplement"
        },
        {
          "label": "Children – Micronutrient Needs | Linus Pauling Institute",
          "url": "https://lpi.oregonstate.edu/mic/life-stages/children"
        },
        {
          "label": "Nutrients for Toddlers – Boys Town Pediatrics",
          "url": "https://www.boystownpediatrics.org/knowledge-center/toddler-nutrition"
        },
        {
          "label": "Vitamin D | Infant and Toddler Nutrition – CDC",
          "url": "https://www.cdc.gov/infant-toddler-nutrition/vitamins-minerals/vitamin-d.html"
        },
        {
          "label": "Iron | Infant and Toddler Nutrition – CDC",
          "url": "https://www.cdc.gov/infant-toddler-nutrition/vitamins-minerals/iron.html"
        },
        {
          "label": "Where We Stand: Vitamin D & Iron Supplements for Babies – HealthyChildren.org",
          "url": "https://www.healthychildren.org/English/ages-stages/baby/feeding-nutrition/Pages/Vitamin-Iron-Supplements.aspx"
        }
      ],
      "related": [
        "growth-supplements-guide-for-families",
        "protein-key-to-child-growth"
      ],
      "suggested": [
        "common-child-nutrition-mistakes-from-infancy-to-adolescence",
        "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years"
      ],
      "approvedBy": "Dr. Hossein Lavasani Far",
      "titleGradientIndices": [
        0,
        3,
        6
      ]
    },
    "wordCount": 2133,
    "toc": [
      {
        "depth": 2,
        "value": "Introduction",
        "id": "introduction"
      },
      {
        "depth": 2,
        "value": "Vitamins and Minerals: The Hidden Engines of Child Growth",
        "id": "vitamins-and-minerals-the-hidden-engines-of-child-growth"
      },
      {
        "depth": 2,
        "value": "Part 1: Essential Vitamins for Child Growth",
        "id": "part-1-essential-vitamins-for-child-growth"
      },
      {
        "depth": 2,
        "value": "Part 2: Essential Minerals for Child Growth",
        "id": "part-2-essential-minerals-for-child-growth"
      },
      {
        "depth": 2,
        "value": "Part 3: Supplements — Food Comes First",
        "id": "part-3-supplements--food-comes-first"
      },
      {
        "depth": 2,
        "value": "Part 4: Practical Tips for Parents",
        "id": "part-4-practical-tips-for-parents"
      },
      {
        "depth": 2,
        "value": "Conclusion",
        "id": "conclusion"
      }
    ]
  },
  {
    "metadata": {
      "title": "قد بلند و رشد سالم؛ نقش ویتامین‌ها در کودکان",
      "description": "برای رشد قد، استخوان‌های قوی و سیستم ایمنی سالم، کودک شما به ترکیب درستی از ویتامین‌ها و مواد معدنی نیاز دارد. در این مقاله، نقش ویتامین‌ها و مینرال‌های کلیدی در رشد کودکان، منابع غذایی آن‌ها و نکات عملی برای والدین را به‌صورت علمی و در عین حال ساده و کاربردی مرور می‌کنیم.",
      "keywords": [
        "ویتامین کودک",
        "رشد قد",
        "مواد معدنی",
        "تغذیه کودک",
        "رشد سالم"
      ],
      "locale": "fa",
      "sharedSlug": "vitamins-and-minerals-for-healthy-child-growth",
      "id": 16,
      "slug": "قد-بلند-و-رشد-سالم-نقش-ویتامین‌ها-در-کودکان",
      "image": "/blogs/vitamins-and-minerals-for-healthy-child-growth/0.png",
      "author": "هومان خوش بین",
      "date": "2025-11-30T00:00:00.000Z",
      "category": "life-style",
      "tags": [
        "پزشکی_کودکان",
        "تغذیه_کودک",
        "رشد_کودک",
        "ویتامین",
        "مواد_معدنی"
      ],
      "resources": [
        {
          "label": "WHO – Micronutrient deficiencies",
          "url": "https://www.who.int/health-topics/micronutrients"
        },
        {
          "label": "WHO – Malnutrition",
          "url": "https://www.who.int/news-room/fact-sheets/detail/malnutrition"
        },
        {
          "label": "CDC – Micronutrients",
          "url": "https://www.cdc.gov/nutrition/micronutrients"
        },
        {
          "label": "NHS – Vitamins for children",
          "url": "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamins-for-children/"
        },
        {
          "label": "NIH – Office of Dietary Supplements",
          "url": "https://ods.od.nih.gov/factsheets/list-all/"
        },
        {
          "label": "Vitamins & minerals for kids & teens",
          "url": "https://raisingchildren.net.au/teens/healthy-lifestyle/nutrients/vitamins-minerals"
        },
        {
          "label": "Does My Child Need a Supplement? – Academy of Nutrition and Dietetics",
          "url": "https://www.eatright.org/health/essential-nutrients/supplements/does-my-child-need-a-supplement"
        },
        {
          "label": "Children – Micronutrient Needs | Linus Pauling Institute",
          "url": "https://lpi.oregonstate.edu/mic/life-stages/children"
        },
        {
          "label": "Nutrients for Toddlers – Boys Town Pediatrics",
          "url": "https://www.boystownpediatrics.org/knowledge-center/toddler-nutrition"
        },
        {
          "label": "Vitamin D | Infant and Toddler Nutrition – CDC",
          "url": "https://www.cdc.gov/infant-toddler-nutrition/vitamins-minerals/vitamin-d.html"
        },
        {
          "label": "Iron | Infant and Toddler Nutrition – CDC",
          "url": "https://www.cdc.gov/infant-toddler-nutrition/vitamins-minerals/iron.html"
        },
        {
          "label": "Where We Stand: Vitamin D & Iron Supplements for Babies – HealthyChildren.org",
          "url": "https://www.healthychildren.org/English/ages-stages/baby/feeding-nutrition/Pages/Vitamin-Iron-Supplements.aspx"
        }
      ],
      "related": [
        "growth-supplements-guide-for-families",
        "protein-key-to-child-growth"
      ],
      "suggested": [
        "common-child-nutrition-mistakes-from-infancy-to-adolescence",
        "healthy-nutrition-for-children-complete-guide-from-birth-to-5-years"
      ],
      "approvedBy": "دکتر حسین لواسانی فر",
      "titleGradientIndices": [
        0,
        3,
        6
      ]
    },
    "wordCount": 3793,
    "toc": [
      {
        "depth": 2,
        "value": "مقدمه",
        "id": "مقدمه"
      },
      {
        "depth": 2,
        "value": "ویتامین‌ها و مواد معدنی؛ موتورهای پنهان رشد کودک",
        "id": "ویتامینها-و-مواد-معدنی-موتورهای-پنهان-رشد-کودک"
      },
      {
        "depth": 2,
        "value": "بخش اول: ویتامین‌های ضروری برای رشد کودک",
        "id": "بخش-اول-ویتامینهای-ضروری-برای-رشد-کودک"
      },
      {
        "depth": 2,
        "value": "بخش دوم: مواد معدنی ضروری برای رشد کودکان",
        "id": "بخش-دوم-مواد-معدنی-ضروری-برای-رشد-کودکان"
      },
      {
        "depth": 2,
        "value": "بخش سوم: مکمل‌ها؛ اولویت همیشه با غذای طبیعی",
        "id": "بخش-سوم-مکملها-اولویت-همیشه-با-غذای-طبیعی"
      },
      {
        "depth": 2,
        "value": "بخش چهارم: توصیه‌های کاربردی برای والدین",
        "id": "بخش-چهارم-توصیههای-کاربردی-برای-والدین"
      },
      {
        "depth": 2,
        "value": "نتیجه‌گیری",
        "id": "نتیجهگیری"
      }
    ]
  }
];
